import type { Node, Edge, TrafficIncident } from "@/types/graph"
import type { TrafficLevel } from "@/types/graph"

export const mockNodes: Node[] = [
  { id: "A", name: "Mumbai", coordinates: [19.076, 72.877], type: "commercial" },
  { id: "B", name: "Delhi", coordinates: [28.613, 77.209], type: "commercial" },
  { id: "C", name: "Bangalore", coordinates: [12.971, 77.594], type: "commercial" },
  { id: "D", name: "Chennai", coordinates: [13.082, 80.27], type: "commercial" },
  { id: "E", name: "Kolkata", coordinates: [22.572, 88.363], type: "commercial" },
  { id: "F", name: "Hyderabad", coordinates: [17.385, 78.486], type: "commercial" },
  { id: "G", name: "Pune", coordinates: [18.52, 73.856], type: "commercial" },
  { id: "H", name: "Ahmedabad", coordinates: [23.022, 72.571], type: "commercial" },
  { id: "I", name: "Jaipur", coordinates: [26.912, 75.787], type: "commercial" },
  { id: "J", name: "Lucknow", coordinates: [26.847, 80.946], type: "commercial" },
]

export const mockEdges: Edge[] = [
  // Mumbai connections
  {
    id: "AB",
    from: "A",
    to: "B",
    distance: 1400,
    baseWeight: 14,
    currentWeight: 14,
    trafficLevel: "moderate" as TrafficLevel,
    roadType: "highway",
    speedLimit: 100,
    lanes: 6,
  },
  {
    id: "AC",
    from: "A",
    to: "C",
    distance: 980,
    baseWeight: 9.8,
    currentWeight: 9.8,
    trafficLevel: "light" as TrafficLevel,
    roadType: "highway",
    speedLimit: 100,
    lanes: 6,
  },
  {
    id: "AG",
    from: "A",
    to: "G",
    distance: 150,
    baseWeight: 1.5,
    currentWeight: 1.5,
    trafficLevel: "free" as TrafficLevel,
    roadType: "highway",
    speedLimit: 100,
    lanes: 6,
  },
  {
    id: "AH",
    from: "A",
    to: "H",
    distance: 530,
    baseWeight: 5.3,
    currentWeight: 5.3,
    trafficLevel: "light" as TrafficLevel,
    roadType: "highway",
    speedLimit: 100,
    lanes: 6,
  },

  // Delhi connections
  {
    id: "BC",
    from: "B",
    to: "C",
    distance: 2100,
    baseWeight: 21,
    currentWeight: 21,
    trafficLevel: "heavy" as TrafficLevel,
    roadType: "highway",
    speedLimit: 100,
    lanes: 6,
  },
  {
    id: "BD",
    from: "B",
    to: "D",
    distance: 2200,
    baseWeight: 22,
    currentWeight: 22,
    trafficLevel: "light" as TrafficLevel,
    roadType: "highway",
    speedLimit: 100,
    lanes: 6,
  },
  {
    id: "BE",
    from: "B",
    to: "E",
    distance: 1500,
    baseWeight: 15,
    currentWeight: 15,
    trafficLevel: "moderate" as TrafficLevel,
    roadType: "highway",
    speedLimit: 100,
    lanes: 6,
  },
  {
    id: "BI",
    from: "B",
    to: "I",
    distance: 280,
    baseWeight: 2.8,
    currentWeight: 2.8,
    trafficLevel: "free" as TrafficLevel,
    roadType: "highway",
    speedLimit: 100,
    lanes: 6,
  },
  {
    id: "BJ",
    from: "B",
    to: "J",
    distance: 550,
    baseWeight: 5.5,
    currentWeight: 5.5,
    trafficLevel: "light" as TrafficLevel,
    roadType: "highway",
    speedLimit: 100,
    lanes: 6,
  },

  // Bangalore connections
  {
    id: "CD",
    from: "C",
    to: "D",
    distance: 350,
    baseWeight: 3.5,
    currentWeight: 3.5,
    trafficLevel: "free" as TrafficLevel,
    roadType: "highway",
    speedLimit: 100,
    lanes: 6,
  },
  {
    id: "CF",
    from: "C",
    to: "F",
    distance: 570,
    baseWeight: 5.7,
    currentWeight: 5.7,
    trafficLevel: "light" as TrafficLevel,
    roadType: "highway",
    speedLimit: 100,
    lanes: 6,
  },

  // Chennai connections
  {
    id: "DE",
    from: "D",
    to: "E",
    distance: 1660,
    baseWeight: 16.6,
    currentWeight: 16.6,
    trafficLevel: "moderate" as TrafficLevel,
    roadType: "highway",
    speedLimit: 100,
    lanes: 6,
  },
  {
    id: "DF",
    from: "D",
    to: "F",
    distance: 630,
    baseWeight: 6.3,
    currentWeight: 6.3,
    trafficLevel: "light" as TrafficLevel,
    roadType: "highway",
    speedLimit: 100,
    lanes: 6,
  },

  // Kolkata connections
  {
    id: "EF",
    from: "E",
    to: "F",
    distance: 1500,
    baseWeight: 15,
    currentWeight: 15,
    trafficLevel: "heavy" as TrafficLevel,
    roadType: "highway",
    speedLimit: 100,
    lanes: 6,
  },
  {
    id: "EJ",
    from: "E",
    to: "J",
    distance: 980,
    baseWeight: 9.8,
    currentWeight: 9.8,
    trafficLevel: "moderate" as TrafficLevel,
    roadType: "highway",
    speedLimit: 100,
    lanes: 6,
  },

  // Pune connections
  {
    id: "GH",
    from: "G",
    to: "H",
    distance: 660,
    baseWeight: 6.6,
    currentWeight: 6.6,
    trafficLevel: "light" as TrafficLevel,
    roadType: "highway",
    speedLimit: 100,
    lanes: 6,
  },

  // Ahmedabad connections
  {
    id: "HI",
    from: "H",
    to: "I",
    distance: 430,
    baseWeight: 4.3,
    currentWeight: 4.3,
    trafficLevel: "free" as TrafficLevel,
    roadType: "highway",
    speedLimit: 100,
    lanes: 6,
  },

  // Jaipur connections
  {
    id: "IJ",
    from: "I",
    to: "J",
    distance: 590,
    baseWeight: 5.9,
    currentWeight: 5.9,
    trafficLevel: "light" as TrafficLevel,
    roadType: "highway",
    speedLimit: 100,
    lanes: 6,
  },

  // Additional cross connections for better routing
  {
    id: "FH",
    from: "F",
    to: "H",
    distance: 780,
    baseWeight: 7.8,
    currentWeight: 7.8,
    trafficLevel: "moderate" as TrafficLevel,
    roadType: "highway",
    speedLimit: 100,
    lanes: 6,
  },
  {
    id: "GF",
    from: "G",
    to: "F",
    distance: 560,
    baseWeight: 5.6,
    currentWeight: 5.6,
    trafficLevel: "light" as TrafficLevel,
    roadType: "highway",
    speedLimit: 100,
    lanes: 6,
  },
]

export const mockIncidents: TrafficIncident[] = [
  {
    id: "inc1",
    type: "accident",
    location: "BC",
    severity: "high",
    description: "Multi-vehicle accident on Delhi-Bangalore highway",
    startTime: new Date(),
    estimatedDuration: 45,
    affectedEdges: ["BC"],
  },
  {
    id: "inc2",
    type: "construction",
    location: "EF",
    severity: "medium",
    description: "Road maintenance on Kolkata-Hyderabad route",
    startTime: new Date(Date.now() - 30 * 60 * 1000),
    estimatedDuration: 120,
    affectedEdges: ["EF"],
  },
]
